### ISSUE TITLE
[Simple restaurant search panel]

### ISSUE THREAD

**Issue by raasoft** [buildo/app-yelposa-buildosa-rick#3]
## requirements

1. The web app needs to search "restaurants" on Yelp by searching for something near a `location` within a certain `radius`.
1. Search list must be updated as long as the user is typing as well as the user presses a search button.
1. In the simplest version, `location` is only a text field.
1. In the simplest version, there are no filters.

A possible (not definitive) UI mockup is showed below:
![image](https://user-images.githubusercontent.com/1053263/42312425-8c9c2e12-8040-11e8-992b-be5197902276.png)

#### Nice to haves:

1. A more accurate input supporting latitude/longitude.
1. Filters section working

## specs

- Restaurant search should be done via Yelp APIs.
- Search must be issued with a debounce of 500 ms after text has changed

## misc
None yet.

## sub-issues

- [x] Search header #4 **[raasoft]**
- [x] Search results list panel #5 **[raasoft]**
- [x] Search business logic #6
